# 测试 lex_word.c
# CFILES += test_word.c
# CFILES += ../lex_word.c
# CFILES += ../../utils/utils_string.c

# CFLAGS += -g
# CFLAGS += -I..
# CFLAGS += -I../../utils

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

# 测试 core_types.c
# CFILES += test_core_types.c

# CFLAGS += -g
# CFLAGS += -I..

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)


# CFILES += test_type.c

# CFLAGS += -g
# CFLAGS += -I..
# CFLAGS += -I../../utils
# CFLAGS += -I../../lex

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)


CFILES += ../../utils/utils_string.c
CFILES += ../../lex/lex.c
CFILES += ../../lex/lex_util.c
CFILES += ../../lex/lex_word.c
CFILES += test_variable.c

CFLAGS += -g
CFLAGS += -I..
CFLAGS += -I../../utils
CFLAGS += -I../../lex

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)
