# 测试 lex_word
CFILES += test_word.c
CFILES += ../lex_word.c
CFILES += ../../utils/utils_string.c

CFLAGS += -g
CFLAGS += -I..
CFLAGS += -I../../utils

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)



