# CFILES += ../utils/utils_string.c
# CFILES += lex.c
# CFILES += lex_util.c
# CFILES += lex_word.c
# CFILES += lex_test.c

# CFLAGS += -g 
# CFLAGS += -I../utils
# CFLAGS += -I../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)



CFILES += ../../utils/utils_string.c
CFILES += ../lex.c
CFILES += ../lex_util.c
CFILES += ../lex_word.c
CFILES += test_lex_word.c

CFLAGS += -g 
CFLAGS += -I..
CFLAGS += -I../../utils
CFLAGS += -I../../core

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)