#ifndef SCF_LEX_WORD_H
#define SCF_LEX_WORD_H


enum lex_words{
    LEX_WORD_PLUS = 0,
    LEX_WORD_MINUS,
    LEX_WORD_STAR,
    LEX_WORD_DIV,
    LEX_WORD_MOD,

    LEX_WORD_INC,
    LEX_WORD_DEC,

    LEX_WORD_SHL,
    LEX_WORD_SHR,

    LEX_WORD_BIT_AND,
    LEX_WORD_BIT_OR,
    LEX_WORD_BIT_NOT,
    
    LEX_WORD_LOGIC_AND,
    LEX_WORD_LOGIC_OR,
    LEX_WORD_LOGIC_NOT,
    LEX_WORD_LOGIC_XOR,

    LEX_WORD_ASSIGN,
    LEX_WORD_ADD_ASSIGN,
    LEX_WORD_SUB_ASSIGN,
    LEX_WORD_MUL_ASSIGN,
    LEX_WORD_DIV_ASSIGN,
    LEX_WORD_MOD_ASSIGN,
    LEX_WORD_SHL_ASSIGN,
    LEX_WORD_SHR_ASSIGN,
    LEX_WORD_BIT_AND_ASSIGN,
    LEX_WORD_BIT_OR_ASSIGN,

    LEX_WORD_LT,
    LEX_WORD_GT,

    LEX_WORD_EQ,
    LEX_WORD_NE,
    LEX_WORD_LE,
    LEX_WORD_GE,

    LEX_WORD_LS,
    LEX_WORD_RS,

    LEX_WORD_LP,
    LEX_WORD_RP,

    LEX_WORD_LA,
    LEX_WORD_RA,

    LEX_WORD_KEY_SIZEOF,
    LEX_WORD_KEY_CREATE,
    LEX_WORD_KEY_CONTAINER,
    LEX_WORD_KEY_VA_ARG,

    LEX_WORD_ARROW,
    LEX_WORD_DOT,

    LEX_WORD_RANGE,
    LEX_WORD_VAR_ARGS,

    LEX_WORD_LB,
    LEX_WORD_RB,

    LEX_WORD_LF,
    LEX_WORD_HASH,
    LEX_WORD_HASH2,

    LEX_WORD_COMMA,
    LEX_WORD_SEMICOLON,
    LEX_WORD_COLON,
    LEX_WORD_SPACE,

    LEX_WORD_EOF,

    LEX_WORD_KEY_IF,
    LEX_WORD_KEY_ELSE,

    LEX_WORD_KEY_FOR,
    LEX_WORD_KEY_DO,
    LEX_WORD_KEY_WHILE,

    LEX_WORD_KEY_BREAK,
    LEX_WORD_KEY_CONTINUE,

    LEX_WORD_KEY_SWITCH,
    LEX_WORD_KEY_CASE,
    LEX_WORD_KEY_DEFAULT,

    LEX_WORD_KEY_RETURN,

    LEX_WORD_KEY_GOTO,

    LEX_WORD_KEY_OPERATOR,
    LEX_WORD_KEY_UNDERLINE,

    LEX_WORD_KEY_INCLUDE,
    LEX_WORD_KEY_DEFINE,
    LEX_WORD_KEY_ENDIF,

    LEX_WORD_KEY_CHAR,

    LEX_WORD_KEY_INT,
    LEX_WORD_KEY_FLOAT,
    LEX_WORD_KEY_DOUBLE,

    LEX_WORD_KEY_INT8,
    LEX_WORD_KEY_INT1,
    LEX_WORD_KEY_INT2,
    LEX_WORD_KEY_INT3,
    LEX_WORD_KEY_INT4,
    LEX_WORD_KEY_INT16,
    LEX_WORD_KEY_INT32,
    LEX_WORD_KEY_INT64,

    LEX_WORD_KEY_UINT8,
    LEX_WORD_KEY_BIT,
    LEX_WORD_KEY_BIT2,
    LEX_WORD_KEY_BIT3,
    LEX_WORD_KEY_BIT4,
    LEX_WORD_KEY_UINT16,
    LEX_WORD_KEY_UINT32,
    LEX_WORD_KEY_UINT64,

    LEX_WORD_KEY_INTPTR,
    LEX_WORD_KEY_UINTPTR,

    LEX_WORD_KEY_VOID,

    LEX_WORD_KEY_VA_START,
    LEX_WORD_KEY_VA_END,

    LEX_WORD_KEY_CLASS,
    
    LEX_WORD_KEY_CONST,
    LEX_WORD_KEY_STATIC,
    LEX_WORD_KEY_EXTERN,
    LEX_WORD_KEY_INLINE,

    LEX_WORD_KEY_ASYNC,
    LEX_WORD_KEY_AWAIT,

    LEX_WORD_KEY_ENUM,
    LEX_WORD_KEY_UNION,
    LEX_WORD_KEY_STRUCT,

    LEX_WORD_KEY_VAR,

    LEX_WORD_CONST_CHAR,

    LEX_WORD_CONST_INT,
    LEX_WORD_CONST_U32,
    LEX_WORD_CONST_I64,
    LEX_WORD_CONST_U64,

    LEX_WORD_CONST_FLOAT,
    LEX_WORD_CONST_DOUBLE,
    LEX_WORD_CONST_COMPLEX,

    LEX_WORD_CONST_STRING,

    LEX_WORD_ID,


};



#endif












