/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: eda.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "eda.pb-c.h"
void   line__init
                     (ScfLine         *message)
{
  static ScfLine init_value = LINE__INIT;
  *message = init_value;
}
size_t line__get_packed_size
                     (const ScfLine *message)
{
  assert(message->base.descriptor == &line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t line__pack
                     (const ScfLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t line__pack_to_buffer
                     (const ScfLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfLine *
       line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfLine *)
     protobuf_c_message_unpack (&line__descriptor,
                                allocator, len, data);
}
void   line__free_unpacked
                     (ScfLine *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   epin__init
                     (ScfEpin         *message)
{
  static ScfEpin init_value = EPIN__INIT;
  *message = init_value;
}
size_t epin__get_packed_size
                     (const ScfEpin *message)
{
  assert(message->base.descriptor == &epin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t epin__pack
                     (const ScfEpin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &epin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t epin__pack_to_buffer
                     (const ScfEpin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &epin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEpin *
       epin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEpin *)
     protobuf_c_message_unpack (&epin__descriptor,
                                allocator, len, data);
}
void   epin__free_unpacked
                     (ScfEpin *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &epin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   econn__init
                     (ScfEconn         *message)
{
  static ScfEconn init_value = ECONN__INIT;
  *message = init_value;
}
size_t econn__get_packed_size
                     (const ScfEconn *message)
{
  assert(message->base.descriptor == &econn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t econn__pack
                     (const ScfEconn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &econn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t econn__pack_to_buffer
                     (const ScfEconn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &econn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEconn *
       econn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEconn *)
     protobuf_c_message_unpack (&econn__descriptor,
                                allocator, len, data);
}
void   econn__free_unpacked
                     (ScfEconn *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &econn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eline__init
                     (ScfEline         *message)
{
  static ScfEline init_value = ELINE__INIT;
  *message = init_value;
}
size_t eline__get_packed_size
                     (const ScfEline *message)
{
  assert(message->base.descriptor == &eline__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eline__pack
                     (const ScfEline *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eline__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eline__pack_to_buffer
                     (const ScfEline *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eline__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEline *
       eline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEline *)
     protobuf_c_message_unpack (&eline__descriptor,
                                allocator, len, data);
}
void   eline__free_unpacked
                     (ScfEline *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &eline__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecomponent__init
                     (ScfEcomponent         *message)
{
  static ScfEcomponent init_value = ECOMPONENT__INIT;
  *message = init_value;
}
size_t ecomponent__get_packed_size
                     (const ScfEcomponent *message)
{
  assert(message->base.descriptor == &ecomponent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecomponent__pack
                     (const ScfEcomponent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ecomponent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecomponent__pack_to_buffer
                     (const ScfEcomponent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ecomponent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEcomponent *
       ecomponent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEcomponent *)
     protobuf_c_message_unpack (&ecomponent__descriptor,
                                allocator, len, data);
}
void   ecomponent__free_unpacked
                     (ScfEcomponent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ecomponent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   efunction__init
                     (ScfEfunction         *message)
{
  static ScfEfunction init_value = EFUNCTION__INIT;
  *message = init_value;
}
size_t efunction__get_packed_size
                     (const ScfEfunction *message)
{
  assert(message->base.descriptor == &efunction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t efunction__pack
                     (const ScfEfunction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &efunction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t efunction__pack_to_buffer
                     (const ScfEfunction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &efunction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEfunction *
       efunction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEfunction *)
     protobuf_c_message_unpack (&efunction__descriptor,
                                allocator, len, data);
}
void   efunction__free_unpacked
                     (ScfEfunction *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &efunction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eboard__init
                     (ScfEboard         *message)
{
  static ScfEboard init_value = EBOARD__INIT;
  *message = init_value;
}
size_t eboard__get_packed_size
                     (const ScfEboard *message)
{
  assert(message->base.descriptor == &eboard__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eboard__pack
                     (const ScfEboard *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eboard__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eboard__pack_to_buffer
                     (const ScfEboard *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eboard__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEboard *
       eboard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEboard *)
     protobuf_c_message_unpack (&eboard__descriptor,
                                allocator, len, data);
}
void   eboard__free_unpacked
                     (ScfEboard *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &eboard__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor line__field_descriptors[4] =
{
  {
    "x0",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, x0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y0",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, y0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, x1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, y1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned line__field_indices_by_name[] = {
  0,   /* field[0] = x0 */
  2,   /* field[2] = x1 */
  1,   /* field[1] = y0 */
  3,   /* field[3] = y1 */
};
static const ProtobufCIntRange line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "line",
  "ScfLine",
  "ScfLine",
  "",
  sizeof(ScfLine),
  4,
  line__field_descriptors,
  line__field_indices_by_name,
  1,  line__number_ranges,
  (ProtobufCMessageInit) line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor epin__field_descriptors[30] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, cid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, lid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tos",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEpin, n_tos),
    offsetof(ScfEpin, tos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_lid",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, c_lid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jv",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, jv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ja",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, ja),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jr",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, jr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uF",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, uf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uH",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, uh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hfe",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, hfe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dr",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, dr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jdr",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, jdr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, sr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jsr",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, jsr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, pr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jpr",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, jpr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    24,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_diodes",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, n_diodes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "l_pos",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, l_pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vflag",
    27,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, vflag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pflag",
    28,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, pflag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vconst",
    29,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, vconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aconst",
    30,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, aconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned epin__field_indices_by_name[] = {
  8,   /* field[8] = a */
  29,   /* field[29] = aconst */
  5,   /* field[5] = c_lid */
  1,   /* field[1] = cid */
  15,   /* field[15] = dr */
  3,   /* field[3] = flags */
  14,   /* field[14] = hfe */
  0,   /* field[0] = id */
  9,   /* field[9] = ja */
  16,   /* field[16] = jdr */
  20,   /* field[20] = jpr */
  11,   /* field[11] = jr */
  18,   /* field[18] = jsr */
  7,   /* field[7] = jv */
  25,   /* field[25] = l_pos */
  2,   /* field[2] = lid */
  24,   /* field[24] = n_diodes */
  21,   /* field[21] = path */
  27,   /* field[27] = pflag */
  19,   /* field[19] = pr */
  10,   /* field[10] = r */
  17,   /* field[17] = sr */
  4,   /* field[4] = tos */
  12,   /* field[12] = uF */
  13,   /* field[13] = uH */
  6,   /* field[6] = v */
  28,   /* field[28] = vconst */
  26,   /* field[26] = vflag */
  22,   /* field[22] = x */
  23,   /* field[23] = y */
};
static const ProtobufCIntRange epin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 30 }
};
const ProtobufCMessageDescriptor epin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "epin",
  "ScfEpin",
  "ScfEpin",
  "",
  sizeof(ScfEpin),
  30,
  epin__field_descriptors,
  epin__field_indices_by_name,
  1,  epin__number_ranges,
  (ProtobufCMessageInit) epin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor econn__field_descriptors[2] =
{
  {
    "lid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEconn, lid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEconn, n_cids),
    offsetof(ScfEconn, cids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned econn__field_indices_by_name[] = {
  1,   /* field[1] = cids */
  0,   /* field[0] = lid */
};
static const ProtobufCIntRange econn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor econn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "econn",
  "ScfEconn",
  "ScfEconn",
  "",
  sizeof(ScfEconn),
  2,
  econn__field_descriptors,
  econn__field_indices_by_name,
  1,  econn__number_ranges,
  (ProtobufCMessageInit) econn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eline__field_descriptors[14] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pins",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEline, n_pins),
    offsetof(ScfEline, pins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_pins",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, c_pins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conns",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEline, n_conns),
    offsetof(ScfEline, conns),
    &econn__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEline, n_lines),
    offsetof(ScfEline, lines),
    &line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEline, v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jv",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEline, jv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEline, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ja",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEline, ja),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vconst",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEline, vconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aconst",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEline, aconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vflag",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEline, vflag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eline__field_indices_by_name[] = {
  9,   /* field[9] = a */
  12,   /* field[12] = aconst */
  2,   /* field[2] = c_pins */
  4,   /* field[4] = color */
  5,   /* field[5] = conns */
  3,   /* field[3] = flags */
  0,   /* field[0] = id */
  10,   /* field[10] = ja */
  8,   /* field[8] = jv */
  6,   /* field[6] = lines */
  1,   /* field[1] = pins */
  7,   /* field[7] = v */
  11,   /* field[11] = vconst */
  13,   /* field[13] = vflag */
};
static const ProtobufCIntRange eline__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor eline__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "eline",
  "ScfEline",
  "ScfEline",
  "",
  sizeof(ScfEline),
  14,
  eline__field_descriptors,
  eline__field_indices_by_name,
  1,  eline__number_ranges,
  (ProtobufCMessageInit) eline__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecomponent__field_descriptors[20] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pins",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEcomponent, n_pins),
    offsetof(ScfEcomponent, pins),
    &epin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jv",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, jv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ja",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, ja),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jr",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, jr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uF",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, uf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uH",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, uh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vflag",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, vflag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lock",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, lock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecomponent__field_indices_by_name[] = {
  6,   /* field[6] = a */
  12,   /* field[12] = color */
  17,   /* field[17] = h */
  0,   /* field[0] = id */
  7,   /* field[7] = ja */
  9,   /* field[9] = jr */
  5,   /* field[5] = jv */
  19,   /* field[19] = lock */
  2,   /* field[2] = model */
  3,   /* field[3] = pins */
  8,   /* field[8] = r */
  13,   /* field[13] = status */
  1,   /* field[1] = type */
  10,   /* field[10] = uF */
  11,   /* field[11] = uH */
  4,   /* field[4] = v */
  18,   /* field[18] = vflag */
  16,   /* field[16] = w */
  14,   /* field[14] = x */
  15,   /* field[15] = y */
};
static const ProtobufCIntRange ecomponent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor ecomponent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ecomponent",
  "ScfEcomponent",
  "ScfEcomponent",
  "",
  sizeof(ScfEcomponent),
  20,
  ecomponent__field_descriptors,
  ecomponent__field_indices_by_name,
  1,  ecomponent__number_ranges,
  (ProtobufCMessageInit) ecomponent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor efunction__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "components",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEfunction, n_components),
    offsetof(ScfEfunction, components),
    &ecomponent__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elines",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEfunction, n_elines),
    offsetof(ScfEfunction, elines),
    &eline__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned efunction__field_indices_by_name[] = {
  1,   /* field[1] = components */
  2,   /* field[2] = elines */
  6,   /* field[6] = h */
  0,   /* field[0] = name */
  5,   /* field[5] = w */
  3,   /* field[3] = x */
  4,   /* field[4] = y */
};
static const ProtobufCIntRange efunction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor efunction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "efunction",
  "ScfEfunction",
  "ScfEfunction",
  "",
  sizeof(ScfEfunction),
  7,
  efunction__field_descriptors,
  efunction__field_indices_by_name,
  1,  efunction__number_ranges,
  (ProtobufCMessageInit) efunction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eboard__field_descriptors[1] =
{
  {
    "functions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEboard, n_functions),
    offsetof(ScfEboard, functions),
    &efunction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eboard__field_indices_by_name[] = {
  0,   /* field[0] = functions */
};
static const ProtobufCIntRange eboard__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor eboard__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "eboard",
  "ScfEboard",
  "ScfEboard",
  "",
  sizeof(ScfEboard),
  1,
  eboard__field_descriptors,
  eboard__field_indices_by_name,
  1,  eboard__number_ranges,
  (ProtobufCMessageInit) eboard__init,
  NULL,NULL,NULL    /* reserved[123] */
};
