# 测试 atomic_test.h
# CFILES += atomic_test.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)


# 测试 graph_test.h
# CFILES += graph_test.c
# CFILES += ../utils_graph.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)



# 测试 list_test.h
# CFILES += stack_test.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)


# 测试 rbtree_test.h
# CFILES += rbtree_test.c
# CFILES += ../utils_rbtree.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

# 测试 stack_test.h
# CFILES += stack_test.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

# 测试 vector_test.h
# CFILES += vector_test.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

# 测试 string_test.h
# CFILES += ../utils_string.c
# CFILES += string_test.c

# CFLAGS += -g 
# CFLAGS += -I../../utils
# CFLAGS += -I../../core

# LDFLAGS +=

# all:
# 	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

# 测试 utils_def.h
CFILES += def_test.c

CFLAGS += -g
CFLAGS += -I../../utils

LDFLAGS +=
all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)
